CREATE DATABASE INTEGRADOR_3
CREATE TABLE PACIENTE
(
  DNI INT NOT NULL,
  NOMBRE INT NOT NULL,
  APELLIDO INT NOT NULL,
  NUM_SS INT NOT NULL,
  PRIMARY KEY (DNI)
);

CREATE TABLE INGRESO
(
  HCL INT NOT NULL,
  DD_HH INT NOT NULL,
  ID_MEDICO INT NOT NULL,
  ID_INGR INT NOT NULL,
  PRIMARY KEY (ID_INGR)
);

CREATE TABLE MEDICO
(
  ID_MEDICO INT NOT NULL,
  MATRICULA INT NOT NULL,
  NOMBRE INT NOT NULL,
  APELLIDO INT NOT NULL,
  ESPECIALIDAD INT NOT NULL,
  PRIMARY KEY (MATRICULA)
);

CREATE TABLE INTERNADO
(
  DD_HH_INGRE INT NOT NULL,
  DIAGNOSTICO INT NOT NULL,
  ID_INT INT NOT NULL,
  DD_HH_ALTA INT NOT NULL,
  QUIRURG INT NOT NULL,
  CLINICO INT NOT NULL,
  MAT_MED INT NOT NULL,
  PRIMARY KEY (ID_INT)
);

CREATE TABLE AMBULATORIO
(
  ID_AMBUL INT NOT NULL,
  1RA_VEZ INT NOT NULL,
  ULTERIOR INT NOT NULL,
  DD_HH INT NOT NULL,
  DIAGNOSTICO INT NOT NULL,
  MAT_MED INT NOT NULL,
  PRIMARY KEY (ID_AMBUL)
);

CREATE TABLE CONSULTA
(
  DNI INT NOT NULL,
  ID_INGR INT NOT NULL,
  PRIMARY KEY (DNI, ID_INGR),
  FOREIGN KEY (DNI) REFERENCES PACIENTE(DNI),
  FOREIGN KEY (ID_INGR) REFERENCES INGRESO(ID_INGR)
);

CREATE TABLE ATIENDE
(
  ID_INGR INT NOT NULL,
  MATRICULA INT NOT NULL,
  PRIMARY KEY (ID_INGR, MATRICULA),
  FOREIGN KEY (ID_INGR) REFERENCES INGRESO(ID_INGR),
  FOREIGN KEY (MATRICULA) REFERENCES MEDICO(MATRICULA)
);

CREATE TABLE DERIV
(
  ID_INGR INT NOT NULL,
  ID_INT INT NOT NULL,
  PRIMARY KEY (ID_INGR, ID_INT),
  FOREIGN KEY (ID_INGR) REFERENCES INGRESO(ID_INGR),
  FOREIGN KEY (ID_INT) REFERENCES INTERNADO(ID_INT)
);

CREATE TABLE DERIV
(
  ID_INGR INT NOT NULL,
  ID_AMBUL INT NOT NULL,
  PRIMARY KEY (ID_INGR, ID_AMBUL),
  FOREIGN KEY (ID_INGR) REFERENCES INGRESO(ID_INGR),
  FOREIGN KEY (ID_AMBUL) REFERENCES AMBULATORIO(ID_AMBUL)
);
