CREATE TABLE PACIENTE
(
  DNI INT NOT NULL,
  NOMBRE varchar(50) NOT NULL,
  APELLIDO varchar(25) NOT NULL,
  NUM_SS varchar(25) NOT NULL,
  PRIMARY KEY (DNI)
);

CREATE TABLE INGRESO
(
  HCL INT NOT NULL,
  DD_HH datetime NOT NULL,
  ID_MEDICO INT NOT NULL,
  ID_INGR INT NOT NULL,
  PRIMARY KEY (ID_INGR)
);

CREATE TABLE MEDICO
(
  ID_MEDICO INT NOT NULL,
  MATRICULA INT NOT NULL,
  NOMBRE varchar(25) NOT NULL,
  APELLIDO varchar(25) NOT NULL,
  ESPECIALIDAD varchar(25) NOT NULL,
  PRIMARY KEY (MATRICULA)
);

CREATE TABLE INTERNADO
(
  DD_HH_INGRE datetime NOT NULL,
  DIAGNOSTICO varchar(25) NOT NULL,
  ID_INT INT NOT NULL,
  DD_HH_ALTA datetime NOT NULL,
  QUIRURG boolean NOT NULL,
  CLINICO boolean NOT NULL,
  MAT_MED INT NOT NULL,
  PRIMARY KEY (ID_INT)
);

CREATE TABLE AMBULATORIO
(
  ID_AMBUL INT NOT NULL,
  1RA_VEZ boolean NOT NULL,
  ULTERIOR boolean NOT NULL,
  DD_HH datetime NOT NULL,
  DIAGNOSTICO varchar(25) NOT NULL,
  MAT_MED INT NOT NULL,
  PRIMARY KEY (ID_AMBUL)
);

CREATE TABLE CONSULTA
(
  DNI INT NOT NULL,
  ID_INGR INT NOT NULL,
  PRIMARY KEY (DNI, ID_INGR),
  FOREIGN KEY (DNI) REFERENCES PACIENTE(DNI),
  FOREIGN KEY (ID_INGR) REFERENCES INGRESO(ID_INGR)
);

CREATE TABLE ATIENDE
(
  ID_INGR INT NOT NULL,
  MATRICULA INT NOT NULL,
  PRIMARY KEY (ID_INGR, MATRICULA),
  FOREIGN KEY (ID_INGR) REFERENCES INGRESO(ID_INGR),
  FOREIGN KEY (MATRICULA) REFERENCES MEDICO(MATRICULA)
);

CREATE TABLE derivInt
(
  ID_INGR INT NOT NULL,
  ID_INT INT NOT NULL,
  PRIMARY KEY (ID_INGR, ID_INT),
  FOREIGN KEY (ID_INGR) REFERENCES INGRESO(ID_INGR),
  FOREIGN KEY (ID_INT) REFERENCES INTERNADO(ID_INT)
);

CREATE TABLE derivAmb
(
  ID_INGR INT NOT NULL,
  ID_AMBUL INT NOT NULL,
  PRIMARY KEY (ID_INGR, ID_AMBUL),
  FOREIGN KEY (ID_INGR) REFERENCES INGRESO(ID_INGR),
  FOREIGN KEY (ID_AMBUL) REFERENCES AMBULATORIO(ID_AMBUL)
);